#:schema node_modules/wrangler/config-schema.json
name = "worker-email"
main = "src/index.tsx"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
 queue = "registration-queue"
 max_batch_size = 10 # optional: defaults to 10
 max_batch_timeout = 5 # optional: defaults to 5 seconds

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true




